refactored signup controllers
Phase-R/Phase-R-Backend pull request #10
Opened 2024-06-30 16:31 UTC by ninsid711

2024-06-30 17:06 UTC, achyuthcodes30 requested changes
Return errors as a gin.H message and use the InitDB function from db modules database package instead of rewriting a connection function. Refer to the Activities service

2024-06-30 17:40 UTC, ninsid711 commented
But the errors are returned as gin.H message along with a http status

2024-07-01 02:45 UTC, ninsid711 commented
the connection function has been removed from signup controller

2024-07-01 04:13 UTC, achyuthcodes30 approved these changes

2024-07-01 04:13 UTC, merged